# Generated by Django 5.0.1 on 2024-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_petproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="petProduct",
        ),
    ]
