# Generated by Django 5.0.1 on 2024-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_delete_petproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
